[builder]
org = "deis"
pull-policy = "IfNotPresent"
docker-tag = "v2.0.0-beta1"

[slugbuilder]
org = "deis"
pull-policy = "IfNotPresent"
docker-tag = "v2.0.0-beta1"

[dockerbuilder]
org = "deis"
pull-policy = "IfNotPresent"
docker-tag = "v2.0.0-beta1"

[controller]
org = "deis"
pull-policy = "IfNotPresent"
docker-tag = "v2.0.0-beta1"

[database]
org = "deis"
pull-policy = "IfNotPresent"
docker-tag = "v2.0.0-beta1"

[registry]
org = "deis"
pull-policy = "IfNotPresent"
docker-tag = "v2.0.0-beta1"

[workflow-manager]
org = "deis"
pull-policy = "IfNotPresent"
docker-tag = "v2.0.0-beta1"
